name: .NET Core

on:
  push:
    branches: [ YJpark1993-patch-1 ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: List out directory content
      run: |
          echo "Listing the contents of the GitHub workspace directory";
          ls ${{ github.workspace }}
          echo "Recursively listing all contents of the current directory";
          ls -R
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

